# Generated by Django 3.1.13 on 2021-12-12 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("circles", "0002_auto_20211129_0302"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime on which the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datetime on which the object was modified",
                        verbose_name="modified at",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "used",
                    models.BooleanField(default=False, verbose_name="Invitation used"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used at"),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="circles.circle",
                        verbose_name="Invitation for circle",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="Circle member that is providind the invitation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invitation sended by",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        help_text="User that used the code to enter to the circle",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invitation used by",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
